main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('stories/', views.stories_index, name='stories_index'),
    path('stories/<int:story_id>/', views.stories_detail, name="detail"),
    path('stories/create/', views.stories_create, name='stories_create'),
    path('stories/<int:pk>/update/', views.StoryUpdate.as_view(), name='stories_update'),
    path('stories/<int:pk>/delete/', views.StoryDelete.as_view(), name='stories_delete'),
    path('stories/<int:story_id>/add_review/', views.add_review, name='add_review'),
    path('stories/<int:story_id>/delete_review/<int:review_id>', views.delete_review, name='delete_review'),
    path('stories/<int:story_id>/update_review/<int:pk>', views.ReviewUpdate.as_view(), name='update_review'),
    path('stories/<int:story_id>/add_favorite/', views.add_favorite, name='add_favorite'),
    path('favorites/', views.favorites_index, name="favorites_index"),
    path('accounts/signup/', views.signup, name='signup'),
    path('user/', views.user_index, name='user_index'),
    path('author/<int:story_id>', views.author_index, name='author_index'),
]

shortlit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

GENRE = (
  ('SF', 'Sci-Fi'),
  ('FA', 'Fantasy'),
  ('HO', 'Horror'),
  ('NF', 'Non-Fiction'),
  ('MY', 'Mystery'),
  ('HU', 'Humour'),
  ('TH', 'Thriller'),
  ('CH', 'Children\'s'),
  ('HF', 'Historical Fiction'),
  ('SP', 'Spiritual'),
  ('RO', 'Romance'),
  ('ME', 'Memoir'),
  ('PO', 'Poetry'),
  ('WE', 'Western'),
  ('YA', 'Young Adult'),
)

RATING = (
  ('1', '1'),
  ('2', '2'),
  ('3', '3'),
  ('4', '4'),
  ('5', '5'),
)


class Story(models.Model):
  title = models.CharField(max_length=50)
  author = models.CharField(max_length=50)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  genre = models.CharField(
    max_length=2,
    choices=GENRE,
    default=GENRE[0][0]
  )
  date = models.DateField('Publish Date')
  content = models.TextField()
  synopsis = models.TextField()
  cover = models.CharField(max_length=200,default="https://i.imgur.com/oDxz1yY.png")

  def get_absolute_url(self):
    return reverse('detail', kwargs={'story_id': self.id})

  def __str__(self):
    return self.title


class Review(models.Model):
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
  content = models.CharField(max_length=250)
  rating = models.CharField(
    max_length=1,
    choices=RATING,
    default=RATING[-1][-1]
  )
  story = models.ForeignKey(Story, on_delete=models.CASCADE)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return f"Content: {self.content}, Rating: {self.rating}"

  def get_absolute_url(self):
    return reverse('detail', kwargs={'story_id': self.story.id})

  class Meta:
    ordering = ['-id']


class Favorite(models.Model):
  user = models.ForeignKey(User, on_delete = models.CASCADE)
  story = models.ForeignKey(Story, on_delete=models.CASCADE)

  def __str__(self):
      return f"ID: {self.id}, Story ID: {self.story.id}"
      

      

main_app/forms.py
from django.forms import ModelForm
from .models import Review, Story

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['content', 'rating']

class StoryForm(ModelForm):
    class Meta:
        model = Story
        exclude = ['user', 'cover']

main_app/views.py
import os
import uuid
import boto3
import requests
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Story, Review, Favorite, User
from .forms import ReviewForm, StoryForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect


def home(request):
  return render(request, 'home.html')


def about(request):
  return render(request, 'about.html')


def stories_index(request):
  stories = Story.objects.all()
  return render(request, 'stories/stories_index.html', {
      'stories': stories
  })


def stories_detail(request, story_id):
  story = Story.objects.get(id=story_id)
  if (request.user.is_anonymous):
    review_form = ReviewForm()
    return render(request, 'stories/detail.html', {
      'story': story,
      'review_form': review_form,
    })
  else:
    
    favs = request.user.favorite_set.all()
    fav = None
    for f in favs:
      if f.story_id == story_id:
        fav = f
    review_form = ReviewForm()
    return render(request, 'stories/detail.html', {
      'story': story,
      'review_form': review_form,
      'fav': fav,
    })


@login_required
def stories_create(request):
  if request.method == 'POST':
    cover_file = request.FILES.get('cover-file', None)
    form = StoryForm(request.POST)
    story = form.save(commit=False)
    if cover_file:
      s3 = boto3.client('s3')
      key = uuid.uuid4().hex[:6] + \
        cover_file.name[cover_file.name.rfind('.'):]
      try:
        s3.upload_fileobj(cover_file, os.environ['S3_BUCKET'], key)
        url = f"{os.environ['S3_BASE_URL']}{os.environ['S3_BUCKET']}/{key}"
        story.cover = url
      except:
        print('An error occurred uploading file to S3')
    story.user = request.user
    story.save()
    return redirect('detail', story_id=story.id)
  else:
    form = StoryForm()
    return render(request, 'main_app/story_form.html', {'form': form})


class StoryUpdate(UpdateView, LoginRequiredMixin):
  model = Story
  fields = ['title', 'author', 'genre', 'date', 'content', 'synopsis']

  def form_valid(self, form):
    if self.request.method == 'POST':
      cover_file = self.request.FILES.get('cover-file', None)
      story = form.save(commit=False)
      print(story.cover)
      if cover_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + \
        cover_file.name[cover_file.name.rfind('.'):]
        try:
          s3.upload_fileobj(cover_file, os.environ['S3_BUCKET'], key)
          url = f"{os.environ['S3_BASE_URL']}{os.environ['S3_BUCKET']}/{key}"
          story.cover = url
          print(story.cover)
        except:
          print('An error occurred uploading file to S3')
      story.save()
      return HttpResponseRedirect(self.get_success_url())


class StoryDelete(DeleteView, LoginRequiredMixin):
  model = Story
  success_url = '/stories/'


@login_required
def add_review(request, story_id):
  form = ReviewForm(request.POST)
  if form.is_valid():
    new_review = form.save(commit=False)
    new_review.story_id = story_id
    new_review.user_id = request.user.id
    new_review.save()
  return redirect('detail', story_id=story_id)


@login_required
def delete_review(request, story_id, review_id):
  Review.objects.get(id=review_id).delete()
  return redirect('detail', story_id=story_id)


class ReviewUpdate(UpdateView, LoginRequiredMixin):
  model = Review
  fields = ['content', 'rating']


def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('stories_index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


@login_required
def add_favorite(request, story_id):
  favorites = request.user.favorite_set.all()
  for fav in favorites:
    if (story_id == fav.__dict__['story_id']):
      fav.delete()
      return redirect('detail', story_id=story_id)
  else:
    fav = Favorite()
    fav.story_id = story_id
    fav.user = request.user
    fav.save()
    return redirect('favorites_index')


@login_required
def favorites_index(request):
  favorites = request.user.favorite_set.all()
  return render(request, 'favorites/favorites_index.html', {'favorites' : favorites})


@login_required
def user_index(request):
  stories = request.user.story_set.all()
  return render(request, 'user/user_index.html', {
      'stories': stories
  })


def author_index(request, story_id):
  author_id = Story.objects.get(id=story_id).user_id
  author = Story.objects.get(id=story_id).user
  stories = Story.objects.filter(user_id=author_id)
  return render(request, 'user/author_index.html', {
      'stories': stories,
      'author': author,
  })

shortlit/main_app/views.py
from django.shortcuts import render
from .models import Story

# Add the following import
from django.http import HttpResponse

# Define the home view
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def stories_index(request):
    stories = Story.objects.all()
    return render(request, 'stories/stories_index.html', {
            'stories': stories
    })

main_app/templates/stories/detail.html
{% extends 'base.html' %}
{% block content %}

  <h1>{{ story.title }}</h1>
  <div class="card brown lighten-5">
    <div class="card-content">
      <img class="pop-out" src="{{ story.cover }}">
      <p>Author: {{ story.author }}</p>
      <p>Synopsis: {{ story.synopsis }}</p>
      <p>Genre: {{ story.get_genre_display }}</p>
      <p>Date: {{ story.date }}</p>
      <pre>Content: {{ story.content }}</pre>
    </div>
    <div class="card-action">
      {% if story.user.id == user.id %}
        <a href="{% url 'stories_update' story.id %}"><i class="material-icons small">edit</i></a>
        <a href="{% url 'stories_delete' story.id %}"><i class="material-icons small">delete</i></a>
        <a class="right" href="{% url 'user_index' %}"><i class="material-icons small">person</i></a>
        {% if fav %}
          <form class="favorite-form" action="{% url 'add_favorite' story.id %}" method="POST">
            {% csrf_token %}
            <button class="remove-fav" type="submit"><i class="material-icons small">remove_circle</i></button>
          </form>
        {% else %}
          <form class="favorite-form" action="{% url 'add_favorite' story.id %}" method="POST">
            {% csrf_token %}
            <button class="favorite-add-remove" type="submit"><i class="material-icons small">favorite</i></button>
          </form>
        {% endif %}
      {% else %}
        {% if fav %}
          <form class="favorite-form" action="{% url 'add_favorite' story.id %}" method="POST">
            {% csrf_token %}
            <button class="remove-fav" type="submit"><i class="material-icons small">remove_circle</i></button>
          </form>
        {% else %}
          <form class="favorite-form" action="{% url 'add_favorite' story.id %}" method="POST">
            {% csrf_token %}
            <button class="favorite-add-remove" type="submit"><i class="material-icons small">favorite</i></button>
          </form>
        {% endif %}
        <a href="{% url 'author_index' story.id %}"><i class="right material-icons">person</i></a>
      {% endif %}
    </div>
  </div>
  <br>
  <br>
  <br>
  <div class="card-panel brown lighten-5">
    <form class="reviews" method="post" action="{% url 'add_review' story.id %}">
      {% csrf_token %}
      {{ review_form.as_p }}
      <button class="right" type="submit"><i class="material-icons">rate_review</i></button>
    </form>
  </div>
  <br>
  <br>
  {% if story.review_set.count %}
    <table>
      <thead>
        <tr>
          <th>Reviews</th>
          <th>Rating</th>
          <th>Created</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for review in story.review_set.all %}
          <tr>
            <td>{{review.content}}</td>
            <td>{{review.rating}}</td>
            <td>{{review.created}}</td>
            <td>
              {% if review.user_id == user.id %}
                <form action="{% url 'update_review' story.id review.id %}" method="POST">
                  {% csrf_token %}
                  <button type="submit"><i class="material-icons">edit</i></button>
                </form>
                <form action="{% url 'delete_review' story.id review.id %}" method="POST">
                  {% csrf_token %}
                  <button type="submit"><i class="material-icons">delete</i></button>
                </form>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <h4>No Reviews Yet</h4>
  {% endif %}

  <script>
    const selectEl = document.getElementById('id_rating');
    M.FormSelect.init(selectEl);
  </script>

{% endblock %}

main_app/templates/stories/stories_index.html
{% extends 'base.html' %}
{% block content %}

  <h1>All Stories</h1>
  <div id="the-test" class="container-index">
    {% for s in stories %}
      <div class="card brown lighten-5">
        <div class="card-content">
          <span class="card-title">
            <a href="/stories/{{ s.id }}">
              <h4>{{ s.title }}</h4>
            </a>
          </span>
          <img src="{{ s.cover }}">
          <div class="book-info">
            <p>Author: {{ s.author }}</p>
            <p>Genre: {{ s.get_genre_display }}</p>
            <p>Publish Date: {{ s.date }}</p>
            <p>Synopsis: <button id="button{{s.id}}">+</button></p>
            <p id="synopsis{{s.id}}">{{ s.synopsis }}</p>
          </div>  
        </div>
      </div>
    {% endfor %}
  </div>

  <script>
    let divEl = document.getElementById('the-test');
    divEl.addEventListener('click', reveal);
    function reveal(evt) {
      let name = evt.target.id;
      let id = name.match(/\d+/);
      let button = document.getElementById(`${name}`);
      let synopsis = document.getElementById(`synopsis${id}`);
      if (synopsis.style.display === "none") {
        button.innerText = "-";
        synopsis.style.display = "block";
      } else if (synopsis.style.display === "block") {
        button.innerText = "+";
        synopsis.style.display = "none";
      } else {
        button.innerText = "-";
        synopsis.style.display = "block";
      }
    }
    const selectEl = document.getElementById('id_genre');
    M.FormSelect.init(selectEl);
  </script>

  {% endblock %}
  